#!/bin/sh

# detector init.d script
# To be installed as /opt/etc/init.d/SXXdetector

# the path to your PS installation directory
PLAYSERVER_DIR=/opt/share/www

RETVAL=0
start() {
echo -n "Starting playserver detector: "
pgrep -f detector.py
RETVAL=$?
[ $RETVAL -eq 0 ] && echo "detector already running: Exiting" && exit 1

# this call actually starts detector.
cd $PLAYSERVER_DIR
python3 $PLAYSERVER_DIR/detector.py &
RETVAL=$?
[ $RETVAL -eq 0 ] && echo -n "done"
echo
return $RETVAL
}

stop() {
echo -n "Stopping playserver detector: "
PID=`pgrep -f detector.py`
[ "x$PID" == "x" ] && echo "playserver detector not found running: Exiting" && exit 1
logger "Entware init.d:" "Stopping playserver detector"
kill $PID
RETVAL=$?
if [ $RETVAL -eq 0 ]
then
        RETVAL=$?
fi
echo
[ $RETVAL -eq 0 ] && echo -n "done"
echo
return $RETVAL
}

# See how we were called.
case "$1" in
start)
start
;;
stop)
stop
;;
restart|reload)
stop
sleep 1
start
RETVAL=$?
;;
check)
pgrep -fa detector.py
RETVAL=$?
;;
*)
echo "Usage: $0 \{start\|stop\|restart\|check\}"
exit 1
;;
esac
exit $RETVAL
