#!/bin/sh

# playserver init.d script
# To be installed as /opt/etc/init.d/SXXplayserver

# the path to your PS installation directory       
PLAYSERVER_DIR=/opt/share/www

RETVAL=0
start() {
echo -n "Starting playserver: "
pgrep -f server.py
RETVAL=$?
[ $RETVAL -eq 0 ] && echo "playserver already running: Exiting" && exit 1

# this call actually starts playserver.
cd $PLAYSERVER_DIR
nohup python3 $PLAYSERVER_DIR/server.py > /dev/null 2>&1 &
RETVAL=$?
[ $RETVAL -eq 0 ] && echo -n "done"
echo
return $RETVAL
}

stop() {
echo -n "Stopping playserver: "
PID=`pgrep -f server.py`
[ "x$PID" == "x" ] && echo "playserver not found running: Exiting" && exit 1
logger "Entware init.d:" "Stopping playserver"
kill $PID
RETVAL=$?
if [ $RETVAL -eq 0 ]
then
	RETVAL=$?
fi
echo
[ $RETVAL -eq 0 ] && echo -n "done"
echo
return $RETVAL
}

# See how we were called.
case "$1" in
start)
start
;;
stop)
stop
;;
restart|reload)
stop
sleep 1
start
RETVAL=$?
;;
check)
pgrep -fa server.py
RETVAL=$?
;;
*)
echo "Usage: $0 \{start\|stop\|restart\|check\}"
exit 1
;;
esac
exit $RETVAL